url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "David Livingstone" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss-v2

permalink: /posts/:title/index:output_ext 

exclude: ["package.json", "postcss.config.js", "tailwind.config.js", "pnpm-lock.yaml", "README.md"]